### ISSUE TITLE
Set up error due to old prepaid account?

### ISSUE THREAD

**Issue by midi** [diederich/moneymoney-monzo#5]
Hi again,

trying to set up Monzo again. Received the account error with the extension from the MoneyMoney website as that didn't have the prepaid fix added yet.
Github version works flawlessly, thanks.

Should I ping the MoneyMoney dev to update the extension, or how would that work?

**Comment by diederich** [comment]
Sorry, thought I did that. Thanks for the heads up @midi!

Und - hey Michael @mrh-line! :-) Would you mind updating the Monzo extension on your website?
